# Generated by Django 3.0.6 on 2020-05-23 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cow', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ourteam',
            name='description',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
